# Generated by Django 5.0.1 on 2024-03-04 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_alter_order_customer_alter_orderitem_customer"),
        ("product", "0003_alter_product_seller"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.RemoveField(
            model_name="order",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.AddField(
            model_name="order",
            name="order",
            field=models.ManyToManyField(to="order.orderitem"),
        ),
        migrations.AddField(
            model_name="order",
            name="ordered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="ordered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orderitem",
                to="product.product",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
