# Generated by Django 5.0.1 on 2024-03-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='orderitem',
        ),
    ]
